import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StoreProvider from "./StoreProvider";
import { useDispatch } from "react-redux";
import { toggleIsLoggedIn } from "@/lib/features/listingsSlice";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Hotels",
  description: "Generated by Kavya",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          {children}
        </StoreProvider>
        
    
        
      </body>
    </html>
  );
}
